<a href="https://colab.research.google.com/github/Fariborz-Eshraghi/Advanced-Dynamics-Project/blob/main/PoliMi_Python_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Python

- High-level language
- Interpreted
- General-Purpose
- Dynamic Typing
- Designed for Readability (White Space matters!)
- Open-Source

# Variables

Variables are used to store data. In Python, they don't require explicit type declaration like in other languages (e.g., C++).

Python supports various built-in data types (int, float, str, bool)


In [ ]:
# Assigning a value to a variable
x = 10  # Integer
y = 3.14  # Float
name = "Robot"  # String
is_active = True  # Boolean
print(is_active, x, y)

True 10 3.14




##### **Task: Define a few variables of different types. Print them to see how they behave**



# Basic Operations

## Standard Math Operations


In [ ]:
# Arithmetic Operations
add = 5 + 3
subtract = 10 - 2
multiplication = 4 * 5
division = 20 / 4
modulus = 7 % 3  # Modulo: returns remainder

You can perform some basic math operations on variables defined earlier

# Control Flow and Functions

## Conditionals

Helps control the flow based on certain conditions (`like if`, `else`)

In [ ]:
# Conditional Statement Example
temperature = 22
if temperature > 30:
    print("It's hot!")
elif temperature > 20 and temperature < 25:
  print("Its not so hot")
else:
    print("It's a comfortable temperature.")

Its not so hot


##### **Task: Write a Python script to process a list of students' grades and assign a status based on their scores**

- Students can fall into these categories (Excellent, Good, Fair, Sufficient, Fail)

## Loops

### For Loop

In [ ]:
# Iterating over a sequence of values (e.g., range, list, etc.).

# Using a for loop to print numbers from 1 to 5
for i in range(1, 6):
    print(i)

1
2
3
4
5


### While Loop

In [ ]:
# Repeatedly execute a block of code as long as a condition is true.

# Using a while loop to print numbers from 1 to 5
i = 10
while i >= 5:
    print(i)
    i -= 1  # Increment to avoid infinite loop

10
9
8
7
6
5


##### **Task: Write a program using a for loop to sum numbers from 1 to 10**

## Functions

Functions are reusable blocks of code that can accept input and return output.

In [ ]:
# Define a function that adds two numbers
def add_and_subtract(a, b):
    sum = a+b
    subtract = a-b
    return sum, subtract

# Calling the function
result_add, result_subtract = add_and_subtract(20, 10)
print(result_add)

30


In [ ]:
# Define a function that adds or multiplies
def add_or_multiply(a, b, operation='add'):
    if operation == 'add':
        return a + b
    elif operation == 'multiply':
        return a * b
    else:
        return "Invalid operation: Not Implemented"


result_add = add_or_multiply(10, 20, 'add')
print("Addition Result:", result_add)

result_multiply = add_or_multiply(10, 20, 'multiply')
print("Multiplication Result:", result_multiply)

result_subtract = add_or_multiply(10, 20, 'subtract')
print("Subtraction Result:", result_subtract)


Addition Result: 30
Multiplication Result: 200
Subtraction Result: Invalid operation: Not Implemented


##### **Task: Write a function `move_robot(position, direction)` that updates the robot’s position on a 2D grid based on the direction "up", "down", "left", or "right", and returns the new position. Call it and print the result**

# Working with Data

## Lists, Arrays, and Dictionaries

Lists are used to store multiple items. Lists are ordered, mutable, and can hold different data types.

In [ ]:
# List Example
numbers = [1, 2, 3, 4, 5]
print(numbers[0])  # Accessing the first element

# Appending an element
numbers.append(6)
print(numbers)

numbers[3] = 20
print(numbers)

1
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 20, 5, 6]


In [ ]:
for i in numbers:
  print(i)

1
2
3
20
5
6


##### **Task: Create a list of numbers from 1 to 5, append a number, and print it**

## NumPy Arrays
NumPy is a powerful library for numerical computing. Used for handling vectors, matrices, tesnors, etc.

In [ ]:
import numpy as np

# Creating NumPy arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
print(arr[-2])
print(arr[1:6])

[ 1  2  3  4  5  6  7  8  9 10]
9
[2 3 4 5 6]


### Manipulating Data

#### Indexing and Slicing
Indexing is used to access specific elements in a NumPy array, while slicing allows you to extract sub-arrays


- Indexing is zero-based (the first element is index 0)

- You can access elements using square brackets `[]`

- You can slice arrays by specifying a range of indices (e.g., `array[start:end]`).

- Slicing follows the pattern where the first index is included, but the last index is not included

In [ ]:
# Create a 2D array (matrix)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accesssing the last row
print(arr[-1])

# Accessing a single element (element at row 1, column 2)
print(arr[1, 2])

# Slicing (select all elements in the second row)
print(arr[1,:])

# Slicing (select the first two rows and the first two columns)
print(arr[:2, :2])

[7 8 9]
6
[4 5 6]
[[1 2]
 [4 5]]


In [ ]:
arr = np.random.rand(3, 3, 3)
arr

array([[[0.56214848, 0.8329652 , 0.30804707],
        [0.5243826 , 0.26210768, 0.55840597],
        [0.00902794, 0.53639287, 0.75703457]],

       [[0.95580384, 0.87086035, 0.65103738],
        [0.55202109, 0.2037795 , 0.60425243],
        [0.66520727, 0.31929351, 0.10397604]],

       [[0.35238902, 0.739037  , 0.01151504],
        [0.98385277, 0.29576468, 0.45826373],
        [0.76303787, 0.1468557 , 0.16730791]]])

In [ ]:
arr[0,1,2]

0.5584059652699794

In [ ]:
np.shape(arr)

(3, 3)

##### **Task: Create a 4x4 matrix of numbers from 1 to 16**
- Access the element at the 3rd row and 2nd column
- Extract the last column of the matrix
- Extract a sub-matrix that includes the first two rows and the last two columns


#### Reshaping Arrays
Reshaping is used to change the shape of an array without changing its data. This is especially useful when preparing data for machine learning models, where you often need to manipulate dimensions

- `np.reshape(new_shape)` returns a new array with the desired shape
- The total number of elements must remain the same before and after reshaping


In [ ]:
# Create a 1D array with 9 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping to 3x3
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)
print("Shape of array before: ", arr.shape)
print("Shape of array after reshaping: ", reshaped_arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array before:  (12,)
Shape of array after reshaping:  (3, 4)


##### **Task: Create a 1D array of 16 elements ranging from 1 to 16**
- Reshape it into a 4x4 array
- Try reshaping it to 4x3 and observe what happens (if incompatible)

#### Element-wise Operations

In NumPy, element-wise operations allow you to perform operations on entire arrays (or sub-arrays) without needing explicit loops

- Operations like addition, multiplication, subtraction, and division are automatically applied element-wise on arrays
- You can also apply functions like `np.sum`, `np.mean`, `np.sqrt`, `np.exp`, etc., element-wise

In [ ]:
# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result = arr1 + arr2  # Element-wise addition
print(result)

# Multiplication (element-wise)
result = arr1 * arr2
print(result)

arr3 = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along rows (axis 1)
print("Sum of arr3 along dimension 1 is: ", np.sum(arr3, axis=1))

# Mean of the entire array
print("Mean of entire arr3 is: ", np.mean(arr3, axis=1))

[5 7 9]
[ 4 10 18]
Sum of arr3 along dimension 1 is:  [ 6 15]
Mean of entire arr3 is:  [2. 5.]


##### **Task: Create two 1D arrays of 5 elements**

- Perform element-wise addition, multiplication, and subtraction between the two arrays
- Create a new array and apply different functions to it, displaying the result

#### Matrix Operations

In [ ]:
# 2x2 Matrix Example
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.dot(A, B) # or np.matmul(A, B)
D = np.cross(A, B)
print(C)
print(D)

[[19 22]
 [43 50]]
[-4 -4]


In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Broadcasting
Broadcasting refers to NumPy's ability to perform element-wise operations on arrays of different shapes. It automatically expands the smaller array to match the shape of the larger one when possible.

- Broadcasting only happens if the dimensions are compatible.
- Smaller arrays are broadcast across the larger arrays to perform element-wise operations.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Adding a 1D array to each row of the 2D array
result = arr + np.array([1, 0, -1])
print(result)

[[2 2 2]
 [5 5 5]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 0, -1])
arr3 = np.array([[1, 0, -1], [1, 0, -1]])

print("First array is : \n",arr, "\nwith Shape of: \n", arr.shape)
print("Second array is : \n",arr2, "\nwith Shape of: \n", arr2.shape)
# Adding a 1D array to each row of the 2D array
result = arr + arr2
print("Adding First and Second array gives : \n",result)

First array is : 
 [[1 2 3]
 [4 5 6]] 
with Shape of: 
 (2, 3)
Second array is : 
 [ 1  0 -1] 
with Shape of: 
 (3,)
Adding First and Second array gives : 
 [[2 2 2]
 [5 5 5]]


- ##### **Task: Create a 3x3 matrix and add a 1D array to it and print result**

- ##### **Task: Create a 2x3 matrix and multiply it by a scalar**

## Dictionaries
A dictionary is a collection of data stored as key-value pairs. It’s ideal for storing data that has a meaningful association between the key (unique identifier) and the value (the data associated with that key)

In [ ]:
# Creating a dictionary with general information
student = {
    "name": "John",
    "age": 23,
    "major": "Mechanical Engineering",
    "grades": [27, 103],
    "is_enrolled": True
}

# Accessing values using keys
print(student["name"])
print(student["grades"])

# Modifying a value (updating the age)
student["age"] = 23
print(student["age"])

# Adding a new key-value pair (adding graduation year)
student["graduation_year"] = 2025
print(student["graduation_year"])

# Deleting a key-value pair (removing enrollment status)
del student["is_enrolled"]

# Displaying the updated dictionary
print(student)


John
[27, 103]
23
2025
{'name': 'John', 'age': 23, 'major': 'Mechanical Engineering', 'grades': [27, 103], 'graduation_year': 2025}


In [ ]:
# Printing dictionary with a for loop
for key, value in student.items():
  print(key, value)

name John
age 23
major Mechanical Engineering
grades [27, 103]
graduation_year 2025


##### **Task: Create a dictionary called travel_info that contains the following information about a trip: Destination `string`, Duration `integer`, Activities `list of strings`, Is Booked `boolean`**

# Object-Oriented Programming
Allows you to structure your code in terms of "objects," which are instances of "classes." This approach organizes code into reusable entities.

## Key Concepts in OOP:

**Class:** A blueprint for creating objects (a particular data structure).

**Object:** An instance of a class, created based on the class blueprint.

**Attributes:** Data stored within an object.

**Methods:** Functions defined inside a class that operate on the attributes



### Defining Classes and Creating Objects

In [ ]:
# Define a class called Robot
class Robot:
    # Class constructor (initializer)
    def __init__(self, name, type_of_robot):
        self.name = name  # Attribute
        self.type_of_robot = type_of_robot  # Attribute

    # A method to display information about the robot
    def display_info(self):
        print(f"Robot Name: {self.name}")
        print(f"Robot Type: {self.type_of_robot}")


# Create objects (instances of the class)
robot1 = Robot("G1", "Humanoid")
robot2 = Robot("Panda", "Manipulator")

# Call the display_info method on each robot
robot1.display_info()
robot2.display_info()

Robot Name: G1
Robot Type: Humanoid
Robot Name: Panda
Robot Type: Manipulator


`__init__`: The constructor method initializes the attributes of the class when an object is created

`self`: Refers to the current instance of the class. It’s used to access attributes and methods in the class.

##### **Task: Create a Robot class with methods to charge the battery and check the robot's status, then create an instance to test these methods**

### Class Inheritance
Inheritance allows one class to inherit the attributes and methods of another class

Child classes can also extend the behavior of base class

In [ ]:
# Base class
class Robot:
    def __init__(self, name, model):
        self.name = name
        self.model = model

    def perform_task(self):
        print(f"{self.name} is performing a general task.")

# Derived class (inherits from Robot)
class CleaningRobot(Robot):
    def __init__(self, name, model, battery_level):
        super().__init__(name, model)
        self.battery_level = battery_level

    def perform_task(self):
        print(f"{self.name} is cleaning the area.")

    def charge(self, amount):
        self.battery_level += amount
        print(f"{self.name}'s battery is now at {self.battery_level}%.")

# Creating an object of the CleaningRobot class
cleaning_robot = CleaningRobot("Roomba", "J9", 50)

# Calling methods
cleaning_robot.perform_task()
cleaning_robot.charge(10)
cleaning_robot.battery_level()

Roomba is cleaning the area.
Roomba's battery is now at 95%.


The `CleaningRobot` class inherits from the base Robot class and gains its properties (`name`, `model`) and methods (`perform_task`)

The CleaningRobot class overrides the `perform_task` method to provide specific functionality for cleaning tasks

It also adds a new method, `charge`, to manage the battery level

##### **Task: Create a parent class and child class**

- Create a parent class Robot with common attributes (`name`, `manufacturer`, `ndof`).
- Then, create child classes for different types of robots: `Manipulator`, `Humanoid`, and `MobileRobot`.
- Each child class should have unique attributes and methods to display robot-specific details.

  **Hints**
- In the parent class, use kwargs to store additional attributes.
- Implement a `display()` method to show both shared and specific details for each robot.
- You can add `max_reach` to `manipulator`, `height` to `Humanoid`, and `max_speed` to `MobileRobot`.
- Instantiate each robot class and print their details.

##### Solutions

In [ ]:
# TASK
def move_robot(position, direction):
    if direction == "up":
        position[1] += 1
    elif direction == "down":
        position[1] -= 1
    elif direction == "left":
        position[0] -= 1
    elif direction == "right":
        position[0] += 1
    return position

robot_position = [0, 0]
print(move_robot(robot_position, "up"))

[0, 1]


In [ ]:
# TASK
class Robot:
    def __init__(self, name, robot_type, battery_level):
        self.name = name
        self.robot_type = robot_type
        self.battery_level = battery_level

    def charge(self, amount):
        self.battery_level += amount
        print(f"{self.name} charged by {amount}%. New battery level: {self.battery_level}%")

    def status_check(self):
        print(f"{self.name} is a {self.robot_type} robot with {self.battery_level}% battery.")

# Create an object (instance) of Robot
robot1 = Robot("Atlas", "Humanoid", 60)

# Call methods
robot1.charge(10)
robot1.status_check()


Atlas charged by 10%. New battery level: 70%
Atlas is a Humanoid robot with 70% battery.


In [ ]:
# TASK
class Robot:
    def __init__(self, name, manufacturer, ndof, **kwargs):
        self.name = name
        self.manufacturer = manufacturer
        self.ndof = ndof
        self.additional_attributes = kwargs  # Store robot-specific attributes as key-value pairs

    def info(self):
        basic_info = f"{self.name} by {self.manufacturer} with {self.ndof} DOF"
        return basic_info

    def display(self):
        info_str = self.info()
        for key, value in self.additional_attributes.items():
            info_str += f", {key}: {value}"
        return info_str

# Manipulator
class Manipulator(Robot):
    def __init__(self, name, manufacturer, ndof, max_reach):
        super().__init__(name, manufacturer, ndof, max_reach=max_reach)

    def manipulator_info(self):
        return self.display()  # Inherits info from Robot and adds arm length

# Humanoid
class Humanoid(Robot):
    def __init__(self, name, manufacturer, ndof, height):
        super().__init__(name, manufacturer, ndof, height=height)

    def humanoid_info(self):
        return self.display()  # Inherits info from Robot and adds height

# MobileRobot
class MobileRobot(Robot):
    def __init__(self, name, manufacturer, ndof, max_speed):
        super().__init__(name, manufacturer, ndof, max_speed=max_speed)

    def mobile_info(self):
        return self.display()  # Inherits info from Robot and adds max speed

# Create instances
manipulator = Manipulator("UR10e", "Universal Robot", 6, max_reach=1.3)
humanoid = Humanoid("H1", "Unitree Robotics", 27, height=1.8)
mobile = MobileRobot("Robo Master", "dji", 4, max_speed=3.5)

# Print robot-specific info
print(manipulator.manipulator_info())
print(humanoid.humanoid_info())
print(mobile.mobile_info())


UR10e by Universal Robot with 6 DOF, max_reach: 1.3
H1 by Unitree Robotics with 27 DOF, height: 1.8
Robo Master by dji with 4 DOF, max_speed: 3.5
